version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/app" 
    schedule:
      interval: "daily"
      time: "09:00" 
    assignees:
      - "beawitcht"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"
    insecure-external-code-execution: "deny"
    ignore:
      - dependency-name: "numpy"