name: Docker CI

on:
  push:
    branches:
      - main
    paths: 
      - 'app/**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          env_file: .env
          envkey_PDF_API_KEY: ${{ secrets.PDF_API_KEY }}
          envkey_RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
          envkey_RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}
          directory: 'app/'
          file: '.env'
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/transinformer_server:latest