name: Push to prod
on:
  push:
    branches:
      - main
    paths: 
      - 'app/**' 

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: pulling image via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
        cd mysite
        git pull https://github.com/beawitcht/transinformed-server.git
        touch ${{ secrets.TOUCH_PATH }}